[package]
name = "server"
version = "0.0.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
bevy_app = { version = "0.15", default-features=false }
bevy_core = { version = "0.15", default-features=false }
bevy_ecs = { version = "0.15", default-features=false }
bevy_log = { version = "0.15", default-features=false }
bevy = { version = "0.15", default-features = false }
bevy_renet = "1.0.0"
bincode = { version = "1.3.3" }
serde = { version = "1.0.210", features = ["derive"] }
rand = "0.8.5"
noise = "0.9.0"
ron = "0.6"
clap = { version = "4.5.19", features = ["derive"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }

# Define the library target
[lib]
name = "server"
path = "src/lib.rs"

# Define the binary target
[[bin]]
name = "server"
path = "src/main.rs"

[lints]
workspace = true